import { format, subDays, subHours } from "date-fns";
import { Order } from "@/types/order";

const now = new Date("2026-06-17T10:00:00");

export const mockOrders: Order[] = [
    {
        id: "ORD-20260610-0001",
        marketOrderId: "NAVER-20260610-1001",
        marketType: "naver",
        storeName: "리빙온마켓",
        orderDate: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "김민수",
        buyerId: "happy_day",
        buyerPhone: "010-1234-5678",
        recipient: {
            name: "김민수",
            phone: "010-1234-5678",
            personalCustomsCode: "P123456789012",
            zipCode: "06234",
            address: "서울특별시 강남구 테헤란로 123",
            detailAddress: "1201호",
            deliveryMessage: "부재 시 문 앞에 놓아주세요.",
        },
        product: {
            id: "PROD-001",
            productOrderId: "NAVER-PROD-1001",
            name: "북유럽 인테리어 TV 거실장 2000",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "화이트 / 2000mm",
            quantity: 1,
            unitPrice: 159000,
            marketLink: "https://smartstore.naver.com",
        },
        paymentPrice: 159000,
        platformFee: 5800,
        expectedSettlement: 153200,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260610-0002",
        marketOrderId: "COUPANG-892123",
        marketType: "coupang",
        storeName: "쿠팡라이프샵",
        orderDate: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "이영희",
        buyerId: "user1234",
        buyerPhone: "010-9876-5432",
        recipient: {
            name: "이영희",
            phone: "010-9876-5432",
            personalCustomsCode: "P987654321098",
            zipCode: "13595",
            address: "경기도 성남시 분당구 정자로 55",
            deliveryMessage: "경비실에 맡겨주세요.",
        },
        product: {
            id: "PROD-002",
            productOrderId: "CP-PROD-892123",
            name: "로봇청소기 X10 Plus 물걸레 겸용",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "화이트 / 기본형",
            quantity: 1,
            unitPrice: 420000,
        },
        paymentPrice: 420000,
        platformFee: 12000,
        expectedSettlement: 408000,
        sourcingLifeSyncStatus: "MATCHING",
    },
    {
        id: "ORD-20260609-0003",
        marketOrderId: "11ST-555555",
        marketType: "11st",
        storeName: "글로벌픽스토어",
        orderDate: format(subDays(now, 1), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 1), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "박서준",
        buyerId: "camp_ready",
        buyerPhone: "010-3333-4444",
        recipient: {
            name: "박서준",
            phone: "010-3333-4444",
            personalCustomsCode: "P333344445555",
            zipCode: "48058",
            address: "부산광역시 해운대구 마린시티2로 33",
            deliveryMessage: "택배함에 넣어주세요.",
        },
        product: {
            id: "PROD-003",
            productOrderId: "11ST-PROD-555555",
            name: "캠핑 접이식 경량 체어 1+1",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "그린 / 2개 세트",
            quantity: 2,
            unitPrice: 45000,
        },
        paymentPrice: 90000,
        platformFee: 3000,
        expectedSettlement: 87000,
        expectedCost: 87696,
        sourcingLifeSyncStatus: "MATCH_SAVED",
        sourcingLifeMatch: {
            candidateId: "ORD-20260609-0003-MATCH-01",
            optionId: "green-2p-1",
            productId: "SL-P-0003-01",
            productName: "캠핑 접이식 경량 체어 1+1",
            thumbnail: "/images/dummy/camping-chair.png",
            matchRate: 94,
            optionName: "그린 / 2개 세트",
            quantity: 2,
            estimatedCost: 43848,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260609-0003&matchId=ORD-20260609-0003-MATCH-01&optionId=green-2p-1",
        },
    },
    {
        id: "ORD-20260608-0004",
        marketOrderId: "NAVER-PAY-0004",
        marketType: "naver",
        storeName: "홈데코랩",
        orderDate: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "최다은",
        buyerId: "mood_light",
        buyerPhone: "010-7777-8888",
        recipient: {
            name: "최다은",
            phone: "010-7777-8888",
            personalCustomsCode: "P777788889999",
            zipCode: "21998",
            address: "인천광역시 연수구 송도과학로 16",
            detailAddress: "A동 803호",
            deliveryMessage: "배송 전 연락 바랍니다.",
        },
        product: {
            id: "PROD-004",
            productOrderId: "NAVER-PROD-0004",
            name: "빈티지 글라스 무드 조명",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "앰버 브라운 / Type B",
            quantity: 1,
            unitPrice: 38000,
        },
        paymentPrice: 38000,
        platformFee: 1200,
        expectedSettlement: 36800,
        expectedCost: 18144,
        sourcingLifeSyncStatus: "PAYMENT_READY",
        sourcingLifeSyncedAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260608-0004-MATCH-01",
            optionId: "amber-b-1",
            productId: "SL-P-0004-01",
            productName: "빈티지 글라스 무드 조명",
            thumbnail: "/images/dummy/vintage-lamp.png",
            matchRate: 98,
            optionName: "앰버 브라운 / Type B",
            quantity: 1,
            estimatedCost: 18144,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260608-0004&matchId=ORD-20260608-0004-MATCH-01&optionId=amber-b-1",
        },
    },
    {
        id: "ORD-20260607-0005",
        marketOrderId: "GMARKET-29384",
        marketType: "gmarket",
        storeName: "지마켓리빙박스",
        orderDate: format(subDays(now, 3), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 3), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "한서준",
        buyerId: "living_jun",
        buyerPhone: "010-1111-2222",
        recipient: {
            name: "한서준",
            phone: "010-1111-2222",
            personalCustomsCode: "P111122223333",
            zipCode: "63309",
            address: "제주특별자치도 제주시 첨단로 242",
            detailAddress: "101동 202호",
            deliveryMessage: "파손 주의 부탁드립니다.",
        },
        product: {
            id: "PROD-005",
            productOrderId: "GMARKET-PROD-29384",
            name: "원목 캣타워 대형 캣폴",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "5단 / 스크래처 추가",
            quantity: 1,
            unitPrice: 129000,
        },
        paymentPrice: 129000,
        platformFee: 4500,
        expectedSettlement: 124500,
        expectedCost: 78500,
        sourcingLifeSyncStatus: "PAID",
        sourcingLifeOrderId: "SL-20260607-2230",
        sourcingLifeSyncedAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 78500,
            currency: "KRW",
            paidAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260606-0006",
        marketOrderId: "CP-SHIP-0006",
        marketType: "coupang",
        storeName: "스마트홈셀러",
        orderDate: format(subDays(now, 4), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 4), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        buyerName: "송건우",
        buyerId: "music_go",
        buyerPhone: "010-1234-4321",
        recipient: {
            name: "송건우",
            phone: "010-1234-4321",
            personalCustomsCode: "INVALID-CODE",
            zipCode: "41931",
            address: "대구광역시 중구 동성로 25",
            deliveryMessage: "문 앞 배송",
        },
        product: {
            id: "PROD-006",
            productOrderId: "CP-PROD-SHIP-0006",
            name: "무선 블루투스 이어폰",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "화이트",
            quantity: 1,
            unitPrice: 35000,
        },
        paymentPrice: 35000,
        platformFee: 1000,
        expectedSettlement: 34000,
        expectedCost: 21000,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "645321684321",
            receivedAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "manual",
        },
    },
    {
        id: "ORD-20260604-0007",
        marketOrderId: "NAVER-DONE-0007",
        marketType: "naver",
        storeName: "리빙온마켓",
        orderDate: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
        status: "DELIVERED",
        buyerName: "정하린",
        buyerId: "shelf_love",
        buyerPhone: "010-2222-7788",
        recipient: {
            name: "정하린",
            phone: "010-2222-7788",
            personalCustomsCode: "P222277778888",
            zipCode: "04321",
            address: "서울특별시 용산구 한강대로 45",
            deliveryMessage: "부재 시 경비실",
        },
        product: {
            id: "PROD-007",
            productOrderId: "NAVER-PROD-DONE-0007",
            name: "미니 선반 수납장",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "화이트 / 3단",
            quantity: 1,
            unitPrice: 29000,
        },
        paymentPrice: 29000,
        platformFee: 900,
        expectedSettlement: 28100,
        expectedCost: 16200,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "408912345678",
            receivedAt: format(subDays(now, 5), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 5), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
        },
    },
    {
        id: "ORD-20260603-0008",
        marketOrderId: "CP-CANCEL-0008",
        marketType: "coupang",
        storeName: "쿠팡라이프샵",
        orderDate: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
        status: "CLAIM",
        buyerName: "문소윤",
        buyerId: "moon_cancel",
        buyerPhone: "010-5555-1212",
        recipient: {
            name: "문소윤",
            phone: "010-5555-1212",
            personalCustomsCode: "P555512121212",
            zipCode: "16488",
            address: "경기도 수원시 팔달구 권광로 100",
            deliveryMessage: "배송 보류 요청",
        },
        product: {
            id: "PROD-008",
            productOrderId: "CP-PROD-CANCEL-0008",
            name: "주방 정리 트레이",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "대형 / 그레이",
            quantity: 1,
            unitPrice: 24000,
        },
        paymentPrice: 24000,
        platformFee: 800,
        expectedSettlement: 23200,
        sourcingLifeSyncStatus: "HOLD",
        claimReason: "구매자 취소 요청",
        failureReason: "클레임 접수로 송장전송 보류",
        claimType: "CANCEL",
        claimStatus: "취소 요청",
        claimRequestedAt: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
        previousStatus: "NEW",
    },
    {
        id: "ORD-20260603-0011",
        marketOrderId: "NAVER-RETURN-0011",
        marketType: "naver",
        storeName: "홈데코랩",
        orderDate: format(subDays(now, 8), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 8), "yyyy-MM-dd HH:mm"),
        status: "CLAIM",
        buyerName: "정반품",
        buyerId: "return_case",
        buyerPhone: "010-1010-1111",
        recipient: {
            name: "정반품",
            phone: "010-1010-1111",
            personalCustomsCode: "P101011112222",
            zipCode: "04783",
            address: "서울특별시 성동구 왕십리로 100",
            deliveryMessage: "회수 요청",
        },
        product: {
            id: "PROD-011",
            productOrderId: "NAVER-PROD-RETURN-0011",
            name: "접이식 수납 박스",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "그레이 / 대형",
            quantity: 2,
            unitPrice: 18500,
        },
        paymentPrice: 37000,
        platformFee: 1200,
        expectedSettlement: 35800,
        expectedCost: 21400,
        sourcingLifeSyncStatus: "HOLD",
        sourcingLifeOrderId: "SL-20260603-0011",
        sourcingLifeSyncedAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 21400,
            currency: "KRW",
            paidAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606030011",
            receivedAt: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
        },
        claimReason: "상품 파손으로 반품 요청",
        failureReason: "반품 요청으로 처리 보류",
        claimType: "RETURN",
        claimStatus: "반품 요청",
        claimRequestedAt: format(subDays(now, 5), "yyyy-MM-dd HH:mm"),
        previousStatus: "DELIVERED",
    },
    {
        id: "ORD-20260602-0012",
        marketOrderId: "11ST-EXCHANGE-0012",
        marketType: "11st",
        storeName: "홈앤키친11",
        orderDate: format(subDays(now, 9), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 9), "yyyy-MM-dd HH:mm"),
        status: "CLAIM",
        buyerName: "이교환",
        buyerId: "exchange_case",
        buyerPhone: "010-2020-2222",
        recipient: {
            name: "이교환",
            phone: "010-2020-2222",
            personalCustomsCode: "P202022223333",
            zipCode: "17006",
            address: "경기도 용인시 기흥구 동백로 10",
            deliveryMessage: "교환 처리 필요",
        },
        product: {
            id: "PROD-012",
            productOrderId: "11ST-PROD-EXCHANGE-0012",
            name: "무선 미니 가습기",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "화이트",
            quantity: 1,
            unitPrice: 31000,
        },
        paymentPrice: 31000,
        platformFee: 1000,
        expectedSettlement: 30000,
        expectedCost: 17600,
        sourcingLifeSyncStatus: "HOLD",
        sourcingLifeOrderId: "SL-20260602-0012",
        sourcingLifeSyncedAt: format(subDays(now, 8), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 17600,
            currency: "KRW",
            paidAt: format(subDays(now, 8), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "512606020012",
            receivedAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "manual",
        },
        claimReason: "색상 오배송으로 교환 요청",
        failureReason: "교환 요청으로 처리 보류",
        claimType: "EXCHANGE",
        claimStatus: "교환 요청",
        claimRequestedAt: format(subDays(now, 4), "yyyy-MM-dd HH:mm"),
        previousStatus: "SHIPPING",
    },
    {
        id: "ORD-20260610-0013",
        marketOrderId: "AUCTION-NEW-0013",
        marketType: "auction",
        storeName: "옥션리빙셀렉트",
        orderDate: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "오지훈",
        buyerId: "office_oh",
        buyerPhone: "010-4444-9911",
        recipient: {
            name: "오지훈",
            phone: "010-4444-9911",
            personalCustomsCode: "P444499991111",
            zipCode: "07212",
            address: "서울특별시 영등포구 선유로 130",
            detailAddress: "7층",
            deliveryMessage: "평일 오후 배송 희망",
        },
        product: {
            id: "PROD-013",
            productOrderId: "AUCTION-PROD-0013",
            name: "높이조절 모니터 받침대",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "블랙 / 서랍형",
            quantity: 1,
            unitPrice: 27800,
        },
        paymentPrice: 27800,
        platformFee: 950,
        expectedSettlement: 26850,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260610-0014",
        marketOrderId: "GMARKET-NEW-0014",
        marketType: "gmarket",
        storeName: "데일리홈마켓",
        orderDate: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "강유나",
        buyerId: "daily_yuna",
        buyerPhone: "010-8080-3344",
        recipient: {
            name: "강유나",
            phone: "010-8080-3344",
            personalCustomsCode: "P808033441234",
            zipCode: "34051",
            address: "대전광역시 유성구 대학로 99",
            deliveryMessage: "문자 후 배송",
        },
        product: {
            id: "PROD-014",
            productOrderId: "GMARKET-PROD-0014",
            name: "스테인리스 주방 선반 2단",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "실버 / 60cm",
            quantity: 1,
            unitPrice: 36200,
        },
        paymentPrice: 36200,
        platformFee: 1200,
        expectedSettlement: 35000,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260610-0015",
        marketOrderId: "NAVER-PREP-0015",
        marketType: "naver",
        storeName: "홈데코랩",
        orderDate: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "윤채원",
        buyerId: "deco_won",
        buyerPhone: "010-6611-7700",
        recipient: {
            name: "윤채원",
            phone: "010-6611-7700",
            personalCustomsCode: "P661177009999",
            zipCode: "31120",
            address: "충청남도 천안시 동남구 만남로 43",
            deliveryMessage: "부재 시 전화 주세요.",
        },
        product: {
            id: "PROD-015",
            productOrderId: "NAVER-PROD-0015",
            name: "패브릭 수납 바스켓 3종 세트",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "베이지 / M+L+XL",
            quantity: 1,
            unitPrice: 24800,
        },
        paymentPrice: 24800,
        platformFee: 850,
        expectedSettlement: 23950,
        expectedCost: 13200,
        sourcingLifeSyncStatus: "MATCH_SAVED",
        sourcingLifeSyncedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260610-0015-MATCH-01",
            optionId: "beige-set",
            productId: "SL-P-0015-01",
            productName: "패브릭 수납 바스켓 3종 세트",
            thumbnail: "/images/dummy/cat-tower.png",
            matchRate: 91,
            optionName: "베이지 / 3종",
            quantity: 1,
            estimatedCost: 13200,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260610-0015",
        },
    },
    {
        id: "ORD-20260610-0016",
        marketOrderId: "11ST-WAIT-0016",
        marketType: "11st",
        storeName: "홈앤키친11",
        orderDate: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "배수현",
        buyerId: "kitchen_bae",
        buyerPhone: "010-9090-1212",
        recipient: {
            name: "배수현",
            phone: "010-9090-1212",
            personalCustomsCode: "P909012129999",
            zipCode: "54966",
            address: "전라북도 전주시 완산구 홍산로 276",
            detailAddress: "302호",
            deliveryMessage: "택배함 이용",
        },
        product: {
            id: "PROD-016",
            productOrderId: "11ST-PROD-0016",
            name: "실리콘 조리도구 6종 세트",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "크림화이트",
            quantity: 1,
            unitPrice: 31900,
        },
        paymentPrice: 31900,
        platformFee: 1100,
        expectedSettlement: 30800,
        expectedCost: 18400,
        sourcingLifeSyncStatus: "PAID",
        sourcingLifeOrderId: "SL-20260610-0016",
        sourcingLifeSyncedAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 18400,
            currency: "KRW",
            paidAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260610-0017",
        marketOrderId: "COUPANG-SHIP-0017",
        marketType: "coupang",
        storeName: "스마트홈셀러",
        orderDate: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        buyerName: "남도현",
        buyerId: "sound_nam",
        buyerPhone: "010-7070-5566",
        recipient: {
            name: "남도현",
            phone: "010-7070-5566",
            personalCustomsCode: "P707055661234",
            zipCode: "51430",
            address: "경상남도 창원시 성산구 중앙대로 151",
            deliveryMessage: "경비실 보관",
        },
        product: {
            id: "PROD-017",
            productOrderId: "CP-PROD-0017",
            name: "USB C타입 멀티 허브",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "7in1 / 스페이스그레이",
            quantity: 1,
            unitPrice: 44900,
        },
        paymentPrice: 44900,
        platformFee: 1500,
        expectedSettlement: 43400,
        expectedCost: 25900,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260610-0017",
        sourcingLifeSyncedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260610-0017-MATCH-01",
            optionId: "usb-hub-7in1-gray",
            productId: "SL-P-0017-01",
            productName: "USB C타입 7in1 멀티 허브 알루미늄 독",
            thumbnail: "/images/dummy/robot-vacuum.png",
            matchRate: 92,
            optionName: "7in1 / 스페이스그레이",
            quantity: 1,
            estimatedCost: 25900,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260610-0017",
        },
        sourcingLifeActualPayment: {
            amount: 25900,
            currency: "KRW",
            paidAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "789012345678",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
            changedTrackingNumber: "789012345679",
        },
    },
    {
        id: "ORD-20260610-0018",
        marketOrderId: "NAVER-DONE-0018",
        marketType: "naver",
        storeName: "리빙온마켓",
        orderDate: format(subHours(now, 12), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 12), "yyyy-MM-dd HH:mm"),
        status: "DELIVERED",
        buyerName: "서아린",
        buyerId: "arin_home",
        buyerPhone: "010-3030-8877",
        recipient: {
            name: "서아린",
            phone: "010-3030-8877",
            personalCustomsCode: "P303088771111",
            zipCode: "10390",
            address: "경기도 고양시 일산서구 킨텍스로 217",
            deliveryMessage: "배송 완료 후 사진 요청",
        },
        product: {
            id: "PROD-018",
            productOrderId: "NAVER-PROD-0018",
            name: "무타공 욕실 코너 선반",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "화이트 / 2개입",
            quantity: 2,
            unitPrice: 16900,
        },
        paymentPrice: 33800,
        platformFee: 1150,
        expectedSettlement: 32650,
        expectedCost: 18800,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        domesticInvoice: {
            carrier: "우체국택배",
            trackingNumber: "607712349999",
            receivedAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
        },
    },
    {
        id: "ORD-20260610-0019",
        marketOrderId: "GMARKET-CLAIM-0019",
        marketType: "gmarket",
        storeName: "지마켓리빙박스",
        orderDate: format(subHours(now, 14), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 14), "yyyy-MM-dd HH:mm"),
        status: "CLAIM",
        buyerName: "임하늘",
        buyerId: "cancel_sky",
        buyerPhone: "010-5151-6262",
        recipient: {
            name: "임하늘",
            phone: "010-5151-6262",
            personalCustomsCode: "P515162629999",
            zipCode: "58674",
            address: "전라남도 목포시 평화로 21",
            deliveryMessage: "발송 전 취소 요청",
        },
        product: {
            id: "PROD-019",
            productOrderId: "GMARKET-PROD-0019",
            name: "다용도 접이식 빨래바구니",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "블루 / 대형",
            quantity: 1,
            unitPrice: 21900,
        },
        paymentPrice: 21900,
        platformFee: 760,
        expectedSettlement: 21140,
        sourcingLifeSyncStatus: "HOLD",
        claimReason: "단순 변심으로 발송 전 취소 요청",
        failureReason: "출고중지 요청으로 발송 처리 보류",
        claimType: "CANCEL",
        claimStatus: "출고중지 요청",
        claimRequestedAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        previousStatus: "READY_TO_SHIP",
    },
    {
        id: "ORD-20260610-0020",
        marketOrderId: "AUCTION-WAIT-0020",
        marketType: "auction",
        storeName: "하우스웨어옥션",
        orderDate: format(subHours(now, 15), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 15), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "노은지",
        buyerId: "house_noh",
        buyerPhone: "010-2323-4545",
        recipient: {
            name: "노은지",
            phone: "010-2323-4545",
            personalCustomsCode: "P232345451234",
            zipCode: "14548",
            address: "경기도 부천시 길주로 210",
            deliveryMessage: "오전 배송 희망",
        },
        product: {
            id: "PROD-020",
            productOrderId: "AUCTION-PROD-0020",
            name: "무타공 키친타월 홀더",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "블랙 / 자석형",
            quantity: 1,
            unitPrice: 18400,
        },
        paymentPrice: 18400,
        platformFee: 650,
        expectedSettlement: 17750,
        expectedCost: 9200,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260610-0020",
        sourcingLifeSyncedAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 9200,
            currency: "KRW",
            paidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606100020",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260610-0021",
        marketOrderId: "NAVER-WAIT-0021",
        marketType: "naver",
        storeName: "리빙온마켓",
        orderDate: format(subHours(now, 16), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 16), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "고민재",
        buyerId: "minjae_go",
        buyerPhone: "010-6767-1212",
        recipient: {
            name: "고민재",
            phone: "010-6767-1212",
            personalCustomsCode: "P676712121111",
            zipCode: "35229",
            address: "대전광역시 서구 둔산로 100",
            deliveryMessage: "부재 시 문 앞",
        },
        product: {
            id: "PROD-021",
            productOrderId: "NAVER-PROD-0021",
            name: "접이식 노트북 거치대",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "실버 / 휴대용",
            quantity: 1,
            unitPrice: 29800,
        },
        paymentPrice: 29800,
        platformFee: 980,
        expectedSettlement: 28820,
        expectedCost: 15100,
        sourcingLifeSyncStatus: "PAID",
        sourcingLifeOrderId: "SL-20260610-0021",
        sourcingLifeSyncedAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 15100,
            currency: "KRW",
            paidAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260610-0022",
        marketOrderId: "COUPANG-WAIT-0022",
        marketType: "coupang",
        storeName: "쿠팡라이프샵",
        orderDate: format(subHours(now, 18), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 18), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "차서연",
        buyerId: "seo_kitchen",
        buyerPhone: "010-4545-9898",
        recipient: {
            name: "차서연",
            phone: "010-4545-9898",
            personalCustomsCode: "P454598981234",
            zipCode: "51139",
            address: "경상남도 창원시 의창구 원이대로 362",
            deliveryMessage: "택배함 보관",
        },
        product: {
            id: "PROD-022",
            productOrderId: "CP-PROD-0022",
            name: "밀폐 보관용기 8종 세트",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "투명 / 8P",
            quantity: 2,
            unitPrice: 22500,
        },
        paymentPrice: 45000,
        platformFee: 1600,
        expectedSettlement: 43400,
        expectedCost: 25800,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260610-0022",
        sourcingLifeSyncedAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 25800,
            currency: "KRW",
            paidAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "512606100022",
            receivedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260610-0023",
        marketOrderId: "11ST-WAIT-0023",
        marketType: "11st",
        storeName: "글로벌픽스토어",
        orderDate: format(subHours(now, 20), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 20), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "문하준",
        buyerId: "camp_moon",
        buyerPhone: "010-1313-8888",
        recipient: {
            name: "문하준",
            phone: "010-1313-8888",
            personalCustomsCode: "P131388881234",
            zipCode: "26460",
            address: "강원특별자치도 원주시 혁신로 50",
            deliveryMessage: "배송 전 연락",
        },
        product: {
            id: "PROD-023",
            productOrderId: "11ST-PROD-0023",
            name: "캠핑 랜턴 충전식 LED",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "카키 / 10000mAh",
            quantity: 1,
            unitPrice: 41200,
        },
        paymentPrice: 41200,
        platformFee: 1400,
        expectedSettlement: 39800,
        expectedCost: 23600,
        sourcingLifeSyncStatus: "PAID",
        sourcingLifeOrderId: "SL-20260610-0023",
        sourcingLifeSyncedAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 23600,
            currency: "KRW",
            paidAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260610-0024",
        marketOrderId: "GMARKET-WAIT-0024",
        marketType: "gmarket",
        storeName: "데일리홈마켓",
        orderDate: format(subHours(now, 22), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 22), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "백지우",
        buyerId: "daily_baek",
        buyerPhone: "010-2424-7777",
        recipient: {
            name: "백지우",
            phone: "010-2424-7777",
            personalCustomsCode: "P242477771234",
            zipCode: "16666",
            address: "경기도 수원시 영통구 광교중앙로 140",
            deliveryMessage: "경비실 보관",
        },
        product: {
            id: "PROD-024",
            productOrderId: "GMARKET-PROD-0024",
            name: "화장대 정리함 아크릴",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "투명 / 3단",
            quantity: 1,
            unitPrice: 26700,
        },
        paymentPrice: 26700,
        platformFee: 880,
        expectedSettlement: 25820,
        expectedCost: 14600,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260610-0024",
        sourcingLifeSyncedAt: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 14600,
            currency: "KRW",
            paidAt: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "우체국택배",
            trackingNumber: "512606100024",
            receivedAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260610-0025",
        marketOrderId: "NAVER-WAIT-0025",
        marketType: "naver",
        storeName: "홈데코랩",
        orderDate: format(subHours(now, 23), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 23), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "성유진",
        buyerId: "light_yujin",
        buyerPhone: "010-9898-3434",
        recipient: {
            name: "성유진",
            phone: "010-9898-3434",
            personalCustomsCode: "P989834341234",
            zipCode: "12106",
            address: "경기도 남양주시 다산중앙로 20",
            deliveryMessage: "문 앞 배송",
        },
        product: {
            id: "PROD-025",
            productOrderId: "NAVER-PROD-0025",
            name: "감성 무드등 리모컨형",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "웜화이트 / 리모컨 포함",
            quantity: 1,
            unitPrice: 34900,
        },
        paymentPrice: 34900,
        platformFee: 1100,
        expectedSettlement: 33800,
        expectedCost: 19200,
        sourcingLifeSyncStatus: "PAID",
        sourcingLifeOrderId: "SL-20260610-0025",
        sourcingLifeSyncedAt: format(subHours(now, 10), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 19200,
            currency: "KRW",
            paidAt: format(subHours(now, 10), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260617-0026",
        marketOrderId: "COUPANG-NEW-0026",
        marketType: "coupang",
        storeName: "coupang_daily_01",
        orderDate: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "윤하린",
        buyerId: "harin_yoon",
        buyerPhone: "010-2626-1717",
        recipient: {
            name: "윤하린",
            phone: "010-2626-1717",
            personalCustomsCode: "P262617171234",
            zipCode: "04782",
            address: "서울특별시 성동구 왕십리로 125",
            detailAddress: "906호",
            deliveryMessage: "문 앞 배송",
        },
        product: {
            id: "PROD-026",
            productOrderId: "COUPANG-PROD-0026",
            name: "주방 싱크대 하부 정리 선반",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "화이트 / 2단",
            quantity: 1,
            unitPrice: 29900,
        },
        paymentPrice: 29900,
        platformFee: 980,
        expectedSettlement: 28920,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260617-0027",
        marketOrderId: "11ST-NEW-0027",
        marketType: "11st",
        storeName: "eleven_global_02",
        orderDate: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "임서아",
        buyerId: "sea_lim",
        buyerPhone: "010-2727-1818",
        recipient: {
            name: "임서아",
            phone: "010-2727-1818",
            zipCode: "34051",
            address: "대전광역시 유성구 대학로 99",
            deliveryMessage: "배송 전 문자 주세요.",
        },
        product: {
            id: "PROD-027",
            productOrderId: "11ST-PROD-0027",
            name: "휴대용 미니 가습기",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "핑크 / 필터 3개 포함",
            quantity: 2,
            unitPrice: 15900,
        },
        paymentPrice: 31800,
        platformFee: 1040,
        expectedSettlement: 30760,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260617-0028",
        marketOrderId: "GMARKET-PREP-0028",
        marketType: "gmarket",
        storeName: "gmarket_home_01",
        orderDate: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "조민재",
        buyerId: "minjae_jo",
        buyerPhone: "010-2828-1919",
        recipient: {
            name: "조민재",
            phone: "010-2828-1919",
            personalCustomsCode: "P282819191234",
            zipCode: "14998",
            address: "경기도 시흥시 배곧4로 32",
            deliveryMessage: "부재 시 경비실",
        },
        product: {
            id: "PROD-028",
            productOrderId: "GMARKET-PROD-0028",
            name: "책상 모니터 받침대",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "월넛 / 서랍형",
            quantity: 1,
            unitPrice: 45900,
        },
        paymentPrice: 45900,
        platformFee: 1520,
        expectedSettlement: 44380,
        expectedCost: 23800,
        sourcingLifeSyncStatus: "MATCH_SAVED",
        sourcingLifeSyncedAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260617-0028-MATCH-01",
            optionId: "walnut-drawer",
            productId: "SL-P-0028-01",
            productName: "책상 모니터 받침대 서랍형",
            thumbnail: "/images/dummy/tv-stand.png",
            matchRate: 96,
            optionName: "월넛 / 서랍형",
            quantity: 1,
            estimatedCost: 23800,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260617-0028",
        },
    },
    {
        id: "ORD-20260617-0029",
        marketOrderId: "AUCTION-PREP-0029",
        marketType: "auction",
        storeName: "auction_pick_02",
        orderDate: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "강수빈",
        buyerId: "subin_kang",
        buyerPhone: "010-2929-2020",
        recipient: {
            name: "강수빈",
            phone: "010-2929-2020",
            personalCustomsCode: "P292920201234",
            zipCode: "61011",
            address: "광주광역시 북구 첨단연신로 108",
            detailAddress: "1204동 803호",
            deliveryMessage: "파손 주의",
        },
        product: {
            id: "PROD-029",
            productOrderId: "AUCTION-PROD-0029",
            name: "접이식 빨래 건조대",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "대형 / 실버",
            quantity: 1,
            unitPrice: 38900,
        },
        paymentPrice: 38900,
        platformFee: 1270,
        expectedSettlement: 37630,
        expectedCost: 21100,
        sourcingLifeSyncStatus: "PAYMENT_READY",
        sourcingLifeSyncedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260617-0029-MATCH-01",
            optionId: "large-silver",
            productId: "SL-P-0029-01",
            productName: "접이식 빨래 건조대 대형",
            thumbnail: "/images/dummy/camping-chair.png",
            matchRate: 91,
            optionName: "대형 / 실버",
            quantity: 1,
            estimatedCost: 21100,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260617-0029",
        },
    },
    {
        id: "ORD-20260617-0030",
        marketOrderId: "NAVER-WAIT-0030",
        marketType: "naver",
        storeName: "naver_living_01",
        orderDate: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "문지호",
        buyerId: "jiho_moon",
        buyerPhone: "010-3030-2121",
        recipient: {
            name: "문지호",
            phone: "010-3030-2121",
            personalCustomsCode: "P303021211234",
            zipCode: "26464",
            address: "강원특별자치도 원주시 혁신로 19",
            deliveryMessage: "문 앞 배송",
        },
        product: {
            id: "PROD-030",
            productOrderId: "NAVER-PROD-0030",
            name: "차량용 무선 충전 거치대",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "블랙 / 송풍구형",
            quantity: 1,
            unitPrice: 27900,
        },
        paymentPrice: 27900,
        platformFee: 920,
        expectedSettlement: 26980,
        expectedCost: 15400,
        sourcingLifeSyncStatus: "PAID",
        sourcingLifeOrderId: "SL-20260617-0030",
        sourcingLifeSyncedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 15400,
            currency: "KRW",
            paidAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260617-0031",
        marketOrderId: "COUPANG-WAIT-0031",
        marketType: "coupang",
        storeName: "coupang_life_02",
        orderDate: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "오유나",
        buyerId: "yuna_oh",
        buyerPhone: "010-3131-2222",
        recipient: {
            name: "오유나",
            phone: "010-3131-2222",
            personalCustomsCode: "P313122221234",
            zipCode: "31168",
            address: "충청남도 천안시 서북구 불당25로 182",
            deliveryMessage: "택배함",
        },
        product: {
            id: "PROD-031",
            productOrderId: "COUPANG-PROD-0031",
            name: "실리콘 조리도구 세트",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "그레이 / 11종",
            quantity: 1,
            unitPrice: 31900,
        },
        paymentPrice: 31900,
        platformFee: 1050,
        expectedSettlement: 30850,
        expectedCost: 16800,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260617-0031",
        sourcingLifeSyncedAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 16800,
            currency: "KRW",
            paidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606170031",
            receivedAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260617-0032",
        marketOrderId: "11ST-WAIT-0032",
        marketType: "11st",
        storeName: "eleven_home_01",
        orderDate: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "신태준",
        buyerId: "taejun_shin",
        buyerPhone: "010-3232-2323",
        recipient: {
            name: "신태준",
            phone: "010-3232-2323",
            personalCustomsCode: "WRONG-PCCC",
            zipCode: "52725",
            address: "경상남도 진주시 진주대로 501",
            deliveryMessage: "부재 시 문 앞",
        },
        product: {
            id: "PROD-032",
            productOrderId: "11ST-PROD-0032",
            name: "휴대용 캠핑 랜턴",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "카키 / 충전식",
            quantity: 2,
            unitPrice: 18900,
        },
        paymentPrice: 37800,
        platformFee: 1250,
        expectedSettlement: 36550,
        expectedCost: 20400,
        sourcingLifeSyncStatus: "PAID",
        sourcingLifeOrderId: "SL-20260617-0032",
        sourcingLifeSyncedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 20400,
            currency: "KRW",
            paidAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260617-0033",
        marketOrderId: "AUCTION-WAIT-0033",
        marketType: "auction",
        storeName: "auction_living_01",
        orderDate: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "배준호",
        buyerId: "junho_bae",
        buyerPhone: "010-3333-2424",
        recipient: {
            name: "배준호",
            phone: "010-3333-2424",
            personalCustomsCode: "P333324241234",
            zipCode: "54896",
            address: "전북특별자치도 전주시 완산구 홍산로 250",
            deliveryMessage: "경비실 보관",
        },
        product: {
            id: "PROD-033",
            productOrderId: "AUCTION-PROD-0033",
            name: "무타공 욕실 선반",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "블랙 / 60cm",
            quantity: 1,
            unitPrice: 24900,
        },
        paymentPrice: 24900,
        platformFee: 810,
        expectedSettlement: 24090,
        expectedCost: 13700,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260617-0033",
        sourcingLifeSyncedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 13700,
            currency: "KRW",
            paidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "512606170033",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            source: "manual",
        },
    },
    {
        id: "ORD-20260617-0034",
        marketOrderId: "GMARKET-SHIP-0034",
        marketType: "gmarket",
        storeName: "gmarket_daily_02",
        orderDate: format(subHours(now, 12), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 12), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        buyerName: "권라희",
        buyerId: "rahee_kwon",
        buyerPhone: "010-3434-2525",
        recipient: {
            name: "권라희",
            phone: "010-3434-2525",
            personalCustomsCode: "P343425251234",
            zipCode: "41566",
            address: "대구광역시 북구 엑스코로 10",
            deliveryMessage: "직접 수령",
        },
        product: {
            id: "PROD-034",
            productOrderId: "GMARKET-PROD-0034",
            name: "스마트 체중계",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "화이트 / 앱연동",
            quantity: 1,
            unitPrice: 32900,
        },
        paymentPrice: 32900,
        platformFee: 1080,
        expectedSettlement: 31820,
        expectedCost: 17800,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260617-0034",
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "512606170034",
            receivedAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "manual",
        },
    },
    {
        id: "ORD-20260617-0035",
        marketOrderId: "NAVER-DONE-0035",
        marketType: "naver",
        storeName: "naver_home_02",
        orderDate: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        status: "DELIVERED",
        buyerName: "서도윤",
        buyerId: "doyoon_seo",
        buyerPhone: "010-3535-2626",
        recipient: {
            name: "서도윤",
            phone: "010-3535-2626",
            personalCustomsCode: "P353526261234",
            zipCode: "08511",
            address: "서울특별시 금천구 가산디지털1로 168",
            detailAddress: "B동 1502호",
            deliveryMessage: "완료 후 문자",
        },
        product: {
            id: "PROD-035",
            productOrderId: "NAVER-PROD-0035",
            name: "데스크 LED 스탠드",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "블랙 / 밝기조절",
            quantity: 1,
            unitPrice: 42900,
        },
        paymentPrice: 42900,
        platformFee: 1410,
        expectedSettlement: 41490,
        expectedCost: 22900,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260617-0035",
        domesticInvoice: {
            carrier: "우체국택배",
            trackingNumber: "512606170035",
            receivedAt: format(subDays(now, 1), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 1), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
        },
    },
];
