import { format, subDays, subHours } from "date-fns";
import { Order } from "@/types/order";

// Keep relative demo dates inside the default seven-day collection window.
const now = new Date("2026-07-15T10:00:00");

const rawMockOrders: Order[] = [
    {
        id: "ORD-20260610-0001",
        marketOrderId: "NAVER-20260610-1001",
        marketType: "naver",
        storeName: "리빙온마켓",
        orderDate: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "김민수",
        buyerId: "happy_day",
        buyerPhone: "010-1234-5678",
        recipient: {
            name: "김민수",
            phone: "010-1234-5678",
            personalCustomsCode: "P123456789012",
            zipCode: "06234",
            address: "서울특별시 강남구 테헤란로 123",
            detailAddress: "1201호",
            deliveryMessage: "부재 시 문 앞에 놓아주세요.",
        },
        product: {
            id: "PROD-001",
            productOrderId: "NAVER-PROD-1001",
            name: "북유럽 인테리어 TV 거실장 2000",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "화이트 / 2000mm",
            quantity: 1,
            unitPrice: 159000,
            marketLink: "https://smartstore.naver.com",
        },
        paymentPrice: 159000,
        platformFee: 5800,
        expectedSettlement: 153200,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260610-0002",
        marketOrderId: "COUPANG-892123",
        marketType: "coupang",
        storeName: "쿠팡라이프샵",
        orderDate: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "이영희",
        buyerId: "user1234",
        buyerPhone: "010-9876-5432",
        recipient: {
            name: "이영희",
            phone: "010-9876-5432",
            personalCustomsCode: "P987654321098",
            zipCode: "13595",
            address: "경기도 성남시 분당구 정자로 55",
            deliveryMessage: "경비실에 맡겨주세요.",
        },
        product: {
            id: "PROD-002",
            productOrderId: "CP-PROD-892123",
            name: "로봇청소기 X10 Plus 물걸레 겸용",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "화이트 / 기본형",
            quantity: 1,
            unitPrice: 420000,
        },
        paymentPrice: 420000,
        platformFee: 12000,
        expectedSettlement: 408000,
        sourcingLifeSyncStatus: "MATCHING",
    },
    {
        id: "ORD-20260609-0003",
        marketOrderId: "11ST-555555",
        marketType: "11st",
        storeName: "글로벌픽스토어",
        orderDate: format(subDays(now, 1), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 1), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "박서준",
        buyerId: "camp_ready",
        buyerPhone: "010-3333-4444",
        recipient: {
            name: "박서준",
            phone: "010-3333-4444",
            personalCustomsCode: "P333344445555",
            zipCode: "48058",
            address: "부산광역시 해운대구 마린시티2로 33",
            deliveryMessage: "택배함에 넣어주세요.",
        },
        product: {
            id: "PROD-003",
            productOrderId: "11ST-PROD-555555",
            name: "캠핑 접이식 경량 체어 1+1",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "그린 / 2개 세트",
            quantity: 2,
            unitPrice: 45000,
        },
        paymentPrice: 90000,
        platformFee: 3000,
        expectedSettlement: 87000,
        expectedCost: 87696,
        sourcingLifeSyncStatus: "PAYMENT_READY",
        sourcingProgressStage: "PAYMENT_WAITING",
        sourcingLifeMatch: {
            candidateId: "ORD-20260609-0003-MATCH-01",
            optionId: "green-2p-1",
            productId: "SL-P-0003-01",
            productName: "캠핑 접이식 경량 체어 1+1",
            thumbnail: "/images/dummy/camping-chair.png",
            matchRate: 94,
            optionName: "그린 / 2개 세트",
            quantity: 2,
            estimatedCost: 43848,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260609-0003&matchId=ORD-20260609-0003-MATCH-01&optionId=green-2p-1",
        },
        sourcingForwarder: {
            code: "sl-weihai-a",
            name: "소싱라이프 위해 A센터",
            receiverName: "SL-A센터",
            phone: "18663144075",
            address: "중국 산동성 웨이하이시 환취구 경제기술개발구 해빈남로 28호 A동 SLA-22018",
        },
        sourcingPaymentRequestedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
    },
    {
        id: "ORD-20260608-0004",
        marketOrderId: "NAVER-PAY-0004",
        marketType: "naver",
        storeName: "홈데코랩",
        orderDate: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "최다은",
        buyerId: "mood_light",
        buyerPhone: "010-7777-8888",
        recipient: {
            name: "최다은",
            phone: "010-7777-8888",
            personalCustomsCode: "P777788889999",
            zipCode: "21998",
            address: "인천광역시 연수구 송도과학로 16",
            detailAddress: "A동 803호",
            deliveryMessage: "배송 전 연락 바랍니다.",
        },
        product: {
            id: "PROD-004",
            productOrderId: "NAVER-PROD-0004",
            name: "빈티지 글라스 무드 조명",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "앰버 브라운 / Type B",
            quantity: 1,
            unitPrice: 38000,
        },
        paymentPrice: 38000,
        platformFee: 1200,
        expectedSettlement: 36800,
        expectedCost: 18144,
        sourcingLifeSyncStatus: "PAYMENT_READY",
        sourcingLifeSyncedAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260608-0004-MATCH-01",
            optionId: "amber-b-1",
            productId: "SL-P-0004-01",
            productName: "빈티지 글라스 무드 조명",
            thumbnail: "/images/dummy/vintage-lamp.png",
            matchRate: 98,
            optionName: "앰버 브라운 / Type B",
            quantity: 1,
            estimatedCost: 18144,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260608-0004&matchId=ORD-20260608-0004-MATCH-01&optionId=amber-b-1",
        },
    },
    {
        id: "ORD-20260607-0005",
        marketOrderId: "GMARKET-29384",
        marketType: "gmarket",
        storeName: "지마켓리빙박스",
        orderDate: format(subDays(now, 3), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 3), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "한서준",
        buyerId: "living_jun",
        buyerPhone: "010-1111-2222",
        recipient: {
            name: "한서준",
            phone: "010-1111-2222",
            personalCustomsCode: "P111122223333",
            zipCode: "63309",
            address: "제주특별자치도 제주시 첨단로 242",
            detailAddress: "101동 202호",
            deliveryMessage: "파손 주의 부탁드립니다.",
        },
        product: {
            id: "PROD-005",
            productOrderId: "GMARKET-PROD-29384",
            name: "원목 캣타워 대형 캣폴",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "5단 / 스크래처 추가",
            quantity: 1,
            unitPrice: 129000,
        },
        paymentPrice: 129000,
        platformFee: 4500,
        expectedSettlement: 124500,
        expectedCost: 78500,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "SOURCED",
        sourcingLifeOrderId: "SL-20260607-2230",
        sourcingLifeSyncedAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606070005",
            receivedAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
        sourcingLifeActualPayment: {
            amount: 78500,
            currency: "KRW",
            paidAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260606-0006",
        marketOrderId: "CP-SHIP-0006",
        marketType: "coupang",
        storeName: "스마트홈셀러",
        orderDate: format(subDays(now, 4), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 4), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DELIVERY",
        buyerName: "송건우",
        buyerId: "music_go",
        buyerPhone: "010-1234-4321",
        recipient: {
            name: "송건우",
            phone: "010-1234-4321",
            personalCustomsCode: "INVALID-CODE",
            zipCode: "41931",
            address: "대구광역시 중구 동성로 25",
            deliveryMessage: "문 앞 배송",
        },
        product: {
            id: "PROD-006",
            productOrderId: "CP-PROD-SHIP-0006",
            name: "무선 블루투스 이어폰",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "화이트",
            quantity: 1,
            unitPrice: 35000,
        },
        paymentPrice: 35000,
        platformFee: 1000,
        expectedSettlement: 34000,
        expectedCost: 21000,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "CHINA_SHIPPING",
        sourcingLifeOrderId: "SL-20260606-0006",
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "645321684321",
            receivedAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "manual",
        },
    },
    {
        id: "ORD-20260604-0007",
        marketOrderId: "NAVER-DONE-0007",
        marketType: "naver",
        storeName: "리빙온마켓",
        orderDate: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
        status: "DELIVERED",
        marketOrderStatus: "DELIVERED",
        buyerName: "정하린",
        buyerId: "shelf_love",
        buyerPhone: "010-2222-7788",
        recipient: {
            name: "정하린",
            phone: "010-2222-7788",
            personalCustomsCode: "P222277778888",
            zipCode: "04321",
            address: "서울특별시 용산구 한강대로 45",
            deliveryMessage: "부재 시 경비실",
        },
        product: {
            id: "PROD-007",
            productOrderId: "NAVER-PROD-DONE-0007",
            name: "미니 선반 수납장",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "화이트 / 3단",
            quantity: 1,
            unitPrice: 29000,
        },
        paymentPrice: 29000,
        platformFee: 900,
        expectedSettlement: 28100,
        expectedCost: 16200,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "DELIVERED",
        sourcingLifeOrderId: "SL-20260604-0007",
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "408912345678",
            receivedAt: format(subDays(now, 5), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 5), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
        },
    },
    {
        id: "ORD-20260603-0008",
        marketOrderId: "CP-CANCEL-0008",
        marketType: "coupang",
        storeName: "쿠팡라이프샵",
        orderDate: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
        status: "CLAIM",
        buyerName: "문소윤",
        buyerId: "moon_cancel",
        buyerPhone: "010-5555-1212",
        recipient: {
            name: "문소윤",
            phone: "010-5555-1212",
            personalCustomsCode: "P555512121212",
            zipCode: "16488",
            address: "경기도 수원시 팔달구 권광로 100",
            deliveryMessage: "배송 보류 요청",
        },
        product: {
            id: "PROD-008",
            productOrderId: "CP-PROD-CANCEL-0008",
            name: "주방 정리 트레이",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "대형 / 그레이",
            quantity: 1,
            unitPrice: 24000,
        },
        paymentPrice: 24000,
        platformFee: 800,
        expectedSettlement: 23200,
        sourcingLifeSyncStatus: "NOT_LINKED",
        claimReason: "구매자 취소 요청",
        failureReason: "클레임 접수로 송장전송 보류",
        claimType: "CANCEL",
        claimStatus: "취소 요청",
        claimRequestedAt: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
        previousStatus: "NEW",
    },
    {
        id: "ORD-20260603-0011",
        marketOrderId: "NAVER-RETURN-0011",
        marketType: "naver",
        storeName: "홈데코랩",
        orderDate: format(subDays(now, 8), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 8), "yyyy-MM-dd HH:mm"),
        status: "CLAIM",
        buyerName: "정반품",
        buyerId: "return_case",
        buyerPhone: "010-1010-1111",
        recipient: {
            name: "정반품",
            phone: "010-1010-1111",
            personalCustomsCode: "P101011112222",
            zipCode: "04783",
            address: "서울특별시 성동구 왕십리로 100",
            deliveryMessage: "회수 요청",
        },
        product: {
            id: "PROD-011",
            productOrderId: "NAVER-PROD-RETURN-0011",
            name: "접이식 수납 박스",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "그레이 / 대형",
            quantity: 2,
            unitPrice: 18500,
        },
        paymentPrice: 37000,
        platformFee: 1200,
        expectedSettlement: 35800,
        expectedCost: 21400,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260603-0011",
        sourcingLifeSyncedAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 21400,
            currency: "KRW",
            paidAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606030011",
            receivedAt: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 6), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
        },
        claimReason: "상품 파손으로 반품 요청",
        failureReason: "반품 요청으로 처리 보류",
        claimType: "RETURN",
        claimStatus: "반품 요청",
        claimRequestedAt: format(subDays(now, 5), "yyyy-MM-dd HH:mm"),
        previousStatus: "DELIVERED",
    },
    {
        id: "ORD-20260602-0012",
        marketOrderId: "11ST-EXCHANGE-0012",
        marketType: "11st",
        storeName: "홈앤키친11",
        orderDate: format(subDays(now, 9), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 9), "yyyy-MM-dd HH:mm"),
        status: "CLAIM",
        buyerName: "이교환",
        buyerId: "exchange_case",
        buyerPhone: "010-2020-2222",
        recipient: {
            name: "이교환",
            phone: "010-2020-2222",
            personalCustomsCode: "P202022223333",
            zipCode: "17006",
            address: "경기도 용인시 기흥구 동백로 10",
            deliveryMessage: "교환 처리 필요",
        },
        product: {
            id: "PROD-012",
            productOrderId: "11ST-PROD-EXCHANGE-0012",
            name: "무선 미니 가습기",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "화이트",
            quantity: 1,
            unitPrice: 31000,
        },
        paymentPrice: 31000,
        platformFee: 1000,
        expectedSettlement: 30000,
        expectedCost: 17600,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260602-0012",
        sourcingLifeSyncedAt: format(subDays(now, 8), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 17600,
            currency: "KRW",
            paidAt: format(subDays(now, 8), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "512606020012",
            receivedAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 7), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "manual",
        },
        claimReason: "색상 오배송으로 교환 요청",
        failureReason: "교환 요청으로 처리 보류",
        claimType: "EXCHANGE",
        claimStatus: "교환 요청",
        claimRequestedAt: format(subDays(now, 4), "yyyy-MM-dd HH:mm"),
        previousStatus: "SHIPPING",
    },
    {
        id: "ORD-20260610-0013",
        marketOrderId: "AUCTION-NEW-0013",
        marketType: "auction",
        storeName: "옥션리빙셀렉트",
        orderDate: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "오지훈",
        buyerId: "office_oh",
        buyerPhone: "010-4444-9911",
        recipient: {
            name: "오지훈",
            phone: "010-4444-9911",
            personalCustomsCode: "P444499991111",
            zipCode: "07212",
            address: "서울특별시 영등포구 선유로 130",
            detailAddress: "7층",
            deliveryMessage: "평일 오후 배송 희망",
        },
        product: {
            id: "PROD-013",
            productOrderId: "AUCTION-PROD-0013",
            name: "높이조절 모니터 받침대",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "블랙 / 서랍형",
            quantity: 1,
            unitPrice: 27800,
        },
        paymentPrice: 27800,
        platformFee: 950,
        expectedSettlement: 26850,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260610-0014",
        marketOrderId: "GMARKET-NEW-0014",
        marketType: "gmarket",
        storeName: "데일리홈마켓",
        orderDate: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "강유나",
        buyerId: "daily_yuna",
        buyerPhone: "010-8080-3344",
        recipient: {
            name: "강유나",
            phone: "010-8080-3344",
            personalCustomsCode: "P808033441234",
            zipCode: "34051",
            address: "대전광역시 유성구 대학로 99",
            deliveryMessage: "문자 후 배송",
        },
        product: {
            id: "PROD-014",
            productOrderId: "GMARKET-PROD-0014",
            name: "스테인리스 주방 선반 2단",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "실버 / 60cm",
            quantity: 1,
            unitPrice: 36200,
        },
        paymentPrice: 36200,
        platformFee: 1200,
        expectedSettlement: 35000,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260610-0015",
        marketOrderId: "NAVER-PREP-0015",
        marketType: "naver",
        storeName: "홈데코랩",
        orderDate: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "윤채원",
        buyerId: "deco_won",
        buyerPhone: "010-6611-7700",
        recipient: {
            name: "윤채원",
            phone: "010-6611-7700",
            personalCustomsCode: "P661177009999",
            zipCode: "31120",
            address: "충청남도 천안시 동남구 만남로 43",
            deliveryMessage: "부재 시 전화 주세요.",
        },
        product: {
            id: "PROD-015",
            productOrderId: "NAVER-PROD-0015",
            name: "패브릭 수납 바스켓 3종 세트",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "베이지 / M+L+XL",
            quantity: 1,
            unitPrice: 24800,
        },
        paymentPrice: 24800,
        platformFee: 850,
        expectedSettlement: 23950,
        expectedCost: 13200,
        sourcingLifeSyncStatus: "MATCH_SAVED",
        sourcingLifeSyncedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260610-0015-MATCH-01",
            optionId: "beige-set",
            productId: "SL-P-0015-01",
            productName: "패브릭 수납 바스켓 3종 세트",
            thumbnail: "/images/dummy/cat-tower.png",
            matchRate: 91,
            optionName: "베이지 / 3종",
            quantity: 1,
            estimatedCost: 13200,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260610-0015",
        },
    },
    {
        id: "ORD-20260610-0016",
        marketOrderId: "11ST-WAIT-0016",
        marketType: "11st",
        storeName: "홈앤키친11",
        orderDate: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "배수현",
        buyerId: "kitchen_bae",
        buyerPhone: "010-9090-1212",
        recipient: {
            name: "배수현",
            phone: "010-9090-1212",
            personalCustomsCode: "P909012129999",
            zipCode: "54966",
            address: "전라북도 전주시 완산구 홍산로 276",
            detailAddress: "302호",
            deliveryMessage: "택배함 이용",
        },
        product: {
            id: "PROD-016",
            productOrderId: "11ST-PROD-0016",
            name: "실리콘 조리도구 6종 세트",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "크림화이트",
            quantity: 1,
            unitPrice: 31900,
        },
        paymentPrice: 31900,
        platformFee: 1100,
        expectedSettlement: 30800,
        expectedCost: 18400,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "SOURCED",
        sourcingLifeOrderId: "SL-20260610-0016",
        sourcingLifeSyncedAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "512606100016",
            receivedAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
        sourcingLifeActualPayment: {
            amount: 18400,
            currency: "KRW",
            paidAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260610-0017",
        marketOrderId: "COUPANG-AUTO-SHIP-0017",
        marketType: "coupang",
        storeName: "스마트홈셀러",
        orderDate: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DELIVERY",
        buyerName: "남도현",
        buyerId: "sound_nam",
        buyerPhone: "010-7070-5566",
        recipient: {
            name: "남도현",
            phone: "010-7070-5566",
            personalCustomsCode: "P707055661234",
            zipCode: "51430",
            address: "경상남도 창원시 성산구 중앙대로 151",
            deliveryMessage: "경비실 보관",
        },
        product: {
            id: "PROD-017",
            productOrderId: "CP-PROD-0017",
            name: "USB C타입 멀티 허브",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "7in1 / 스페이스그레이",
            quantity: 1,
            unitPrice: 44900,
        },
        paymentPrice: 44900,
        platformFee: 1500,
        expectedSettlement: 43400,
        expectedCost: 25900,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingLifeOrderId: "SL-20260610-0017",
        sourcingLifeSyncedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260610-0017-MATCH-01",
            optionId: "usb-hub-7in1-gray",
            productId: "SL-P-0017-01",
            productName: "USB C타입 7in1 멀티 허브 알루미늄 독",
            thumbnail: "/images/dummy/robot-vacuum.png",
            matchRate: 92,
            optionName: "7in1 / 스페이스그레이",
            quantity: 1,
            estimatedCost: 25900,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260610-0017",
        },
        sourcingLifeActualPayment: {
            amount: 25900,
            currency: "KRW",
            paidAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "789012345678",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
        },
    },
    {
        id: "ORD-20260610-0018",
        marketOrderId: "NAVER-DONE-0018",
        marketType: "naver",
        storeName: "리빙온마켓",
        orderDate: format(subHours(now, 12), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 12), "yyyy-MM-dd HH:mm"),
        status: "DELIVERED",
        marketOrderStatus: "DELIVERED",
        buyerName: "서아린",
        buyerId: "arin_home",
        buyerPhone: "010-3030-8877",
        recipient: {
            name: "서아린",
            phone: "010-3030-8877",
            personalCustomsCode: "P303088771111",
            zipCode: "10390",
            address: "경기도 고양시 일산서구 킨텍스로 217",
            deliveryMessage: "배송 완료 후 사진 요청",
        },
        product: {
            id: "PROD-018",
            productOrderId: "NAVER-PROD-0018",
            name: "무타공 욕실 코너 선반",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "화이트 / 2개입",
            quantity: 2,
            unitPrice: 16900,
        },
        paymentPrice: 33800,
        platformFee: 1150,
        expectedSettlement: 32650,
        expectedCost: 18800,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "DELIVERED",
        sourcingLifeOrderId: "SL-20260610-0018",
        domesticInvoice: {
            carrier: "우체국택배",
            trackingNumber: "607712349999",
            receivedAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
        },
    },
    {
        id: "ORD-20260610-0019",
        marketOrderId: "GMARKET-CLAIM-0019",
        marketType: "gmarket",
        storeName: "지마켓리빙박스",
        orderDate: format(subHours(now, 14), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 14), "yyyy-MM-dd HH:mm"),
        status: "CLAIM",
        buyerName: "임하늘",
        buyerId: "cancel_sky",
        buyerPhone: "010-5151-6262",
        recipient: {
            name: "임하늘",
            phone: "010-5151-6262",
            personalCustomsCode: "P515162629999",
            zipCode: "58674",
            address: "전라남도 목포시 평화로 21",
            deliveryMessage: "발송 전 취소 요청",
        },
        product: {
            id: "PROD-019",
            productOrderId: "GMARKET-PROD-0019",
            name: "다용도 접이식 빨래바구니",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "블루 / 대형",
            quantity: 1,
            unitPrice: 21900,
        },
        paymentPrice: 21900,
        platformFee: 760,
        expectedSettlement: 21140,
        sourcingLifeSyncStatus: "NOT_LINKED",
        claimReason: "단순 변심으로 발송 전 취소 요청",
        failureReason: "출고중지 요청으로 발송 처리 보류",
        claimType: "CANCEL",
        claimStatus: "출고중지 요청",
        claimRequestedAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        previousStatus: "READY_TO_SHIP",
    },
    {
        id: "ORD-20260610-0020",
        marketOrderId: "AUCTION-WAIT-0020",
        marketType: "auction",
        storeName: "하우스웨어옥션",
        orderDate: format(subHours(now, 15), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 15), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "노은지",
        buyerId: "house_noh",
        buyerPhone: "010-2323-4545",
        recipient: {
            name: "노은지",
            phone: "010-2323-4545",
            personalCustomsCode: "P232345451234",
            zipCode: "14548",
            address: "경기도 부천시 길주로 210",
            deliveryMessage: "오전 배송 희망",
        },
        product: {
            id: "PROD-020",
            productOrderId: "AUCTION-PROD-0020",
            name: "무타공 키친타월 홀더",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "블랙 / 자석형",
            quantity: 1,
            unitPrice: 18400,
        },
        paymentPrice: 18400,
        platformFee: 650,
        expectedSettlement: 17750,
        expectedCost: 9200,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "CHINA_SHIPPING",
        sourcingLifeOrderId: "SL-20260610-0020",
        sourcingLifeSyncedAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 9200,
            currency: "KRW",
            paidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606100020",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260610-0021",
        marketOrderId: "NAVER-WAIT-0021",
        marketType: "naver",
        storeName: "리빙온마켓",
        orderDate: format(subHours(now, 16), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 16), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "고민재",
        buyerId: "minjae_go",
        buyerPhone: "010-6767-1212",
        recipient: {
            name: "고민재",
            phone: "010-6767-1212",
            personalCustomsCode: "P676712121111",
            zipCode: "35229",
            address: "대전광역시 서구 둔산로 100",
            deliveryMessage: "부재 시 문 앞",
        },
        product: {
            id: "PROD-021",
            productOrderId: "NAVER-PROD-0021",
            name: "접이식 노트북 거치대",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "실버 / 휴대용",
            quantity: 1,
            unitPrice: 29800,
        },
        paymentPrice: 29800,
        platformFee: 980,
        expectedSettlement: 28820,
        expectedCost: 15100,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "SOURCED",
        sourcingLifeOrderId: "SL-20260610-0021",
        sourcingLifeSyncedAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "512606100021",
            receivedAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
        sourcingLifeActualPayment: {
            amount: 15100,
            currency: "KRW",
            paidAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260610-0022",
        marketOrderId: "COUPANG-WAIT-0022",
        marketType: "coupang",
        storeName: "쿠팡라이프샵",
        orderDate: format(subHours(now, 18), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 18), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "차서연",
        buyerId: "seo_kitchen",
        buyerPhone: "010-4545-9898",
        recipient: {
            name: "차서연",
            phone: "010-4545-9898",
            personalCustomsCode: "P454598981234",
            zipCode: "51139",
            address: "경상남도 창원시 의창구 원이대로 362",
            deliveryMessage: "택배함 보관",
        },
        product: {
            id: "PROD-022",
            productOrderId: "CP-PROD-0022",
            name: "밀폐 보관용기 8종 세트",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "투명 / 8P",
            quantity: 2,
            unitPrice: 22500,
        },
        paymentPrice: 45000,
        platformFee: 1600,
        expectedSettlement: 43400,
        expectedCost: 25800,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "CUSTOMS_CLEARANCE",
        sourcingLifeOrderId: "SL-20260610-0022",
        sourcingLifeSyncedAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 25800,
            currency: "KRW",
            paidAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "512606100022",
            receivedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260610-0023",
        marketOrderId: "11ST-WAIT-0023",
        marketType: "11st",
        storeName: "글로벌픽스토어",
        orderDate: format(subHours(now, 20), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 20), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "문하준",
        buyerId: "camp_moon",
        buyerPhone: "010-1313-8888",
        recipient: {
            name: "문하준",
            phone: "010-1313-8888",
            personalCustomsCode: "P131388881234",
            zipCode: "26460",
            address: "강원특별자치도 원주시 혁신로 50",
            deliveryMessage: "배송 전 연락",
        },
        product: {
            id: "PROD-023",
            productOrderId: "11ST-PROD-0023",
            name: "캠핑 랜턴 충전식 LED",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "카키 / 10000mAh",
            quantity: 1,
            unitPrice: 41200,
        },
        paymentPrice: 41200,
        platformFee: 1400,
        expectedSettlement: 39800,
        expectedCost: 23600,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "SOURCED",
        sourcingLifeOrderId: "SL-20260610-0023",
        sourcingLifeSyncedAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "우체국택배",
            trackingNumber: "512606100023",
            receivedAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
        sourcingLifeActualPayment: {
            amount: 23600,
            currency: "KRW",
            paidAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260610-0024",
        marketOrderId: "GMARKET-WAIT-0024",
        marketType: "gmarket",
        storeName: "데일리홈마켓",
        orderDate: format(subHours(now, 22), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 22), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "백지우",
        buyerId: "daily_baek",
        buyerPhone: "010-2424-7777",
        recipient: {
            name: "백지우",
            phone: "010-2424-7777",
            personalCustomsCode: "P242477771234",
            zipCode: "16666",
            address: "경기도 수원시 영통구 광교중앙로 140",
            deliveryMessage: "경비실 보관",
        },
        product: {
            id: "PROD-024",
            productOrderId: "GMARKET-PROD-0024",
            name: "화장대 정리함 아크릴",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "투명 / 3단",
            quantity: 1,
            unitPrice: 26700,
        },
        paymentPrice: 26700,
        platformFee: 880,
        expectedSettlement: 25820,
        expectedCost: 14600,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "CUSTOMS_CLEARANCE",
        sourcingLifeOrderId: "SL-20260610-0024",
        sourcingLifeSyncedAt: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 14600,
            currency: "KRW",
            paidAt: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "우체국택배",
            trackingNumber: "512606100024",
            receivedAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260610-0025",
        marketOrderId: "NAVER-WAIT-0025",
        marketType: "naver",
        storeName: "홈데코랩",
        orderDate: format(subHours(now, 23), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 23), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "성유진",
        buyerId: "light_yujin",
        buyerPhone: "010-9898-3434",
        recipient: {
            name: "성유진",
            phone: "010-9898-3434",
            personalCustomsCode: "P989834341234",
            zipCode: "12106",
            address: "경기도 남양주시 다산중앙로 20",
            deliveryMessage: "문 앞 배송",
        },
        product: {
            id: "PROD-025",
            productOrderId: "NAVER-PROD-0025",
            name: "감성 무드등 리모컨형",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "웜화이트 / 리모컨 포함",
            quantity: 1,
            unitPrice: 34900,
        },
        paymentPrice: 34900,
        platformFee: 1100,
        expectedSettlement: 33800,
        expectedCost: 19200,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "SOURCED",
        sourcingLifeOrderId: "SL-20260610-0025",
        sourcingLifeSyncedAt: format(subHours(now, 10), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606100025",
            receivedAt: format(subHours(now, 10), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
        sourcingLifeActualPayment: {
            amount: 19200,
            currency: "KRW",
            paidAt: format(subHours(now, 10), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260617-0026",
        marketOrderId: "COUPANG-NEW-0026",
        marketType: "coupang",
        storeName: "coupang_daily_01",
        orderDate: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "윤하린",
        buyerId: "harin_yoon",
        buyerPhone: "010-2626-1717",
        recipient: {
            name: "윤하린",
            phone: "010-2626-1717",
            personalCustomsCode: "P262617171234",
            zipCode: "04782",
            address: "서울특별시 성동구 왕십리로 125",
            detailAddress: "906호",
            deliveryMessage: "문 앞 배송",
        },
        product: {
            id: "PROD-026",
            productOrderId: "COUPANG-PROD-0026",
            name: "일본 직수입 아보카도 그린 생일 케이크 보온 보냉 가방",
            thumbnail: "/images/product-placeholder.svg",
            optionName: "지퍼형【아보카도 그린】5인치 방수",
            quantity: 1,
            unitPrice: 10000,
        },
        paymentPrice: 10000,
        platformFee: 589,
        expectedSettlement: 9411,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260617-0027",
        marketOrderId: "11ST-NEW-0027",
        marketType: "11st",
        storeName: "eleven_global_02",
        orderDate: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        status: "NEW",
        buyerName: "임서아",
        buyerId: "sea_lim",
        buyerPhone: "010-2727-1818",
        recipient: {
            name: "임서아",
            phone: "010-2727-1818",
            zipCode: "34051",
            address: "대전광역시 유성구 대학로 99",
            deliveryMessage: "배송 전 문자 주세요.",
        },
        product: {
            id: "PROD-027",
            productOrderId: "11ST-PROD-0027",
            name: "휴대용 미니 가습기",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "핑크 / 필터 3개 포함",
            quantity: 2,
            unitPrice: 15900,
        },
        paymentPrice: 31800,
        platformFee: 1040,
        expectedSettlement: 30760,
        sourcingLifeSyncStatus: "NOT_LINKED",
    },
    {
        id: "ORD-20260617-0028",
        marketOrderId: "GMARKET-PREP-0028",
        marketType: "gmarket",
        storeName: "gmarket_home_01",
        orderDate: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "조민재",
        buyerId: "minjae_jo",
        buyerPhone: "010-2828-1919",
        recipient: {
            name: "조민재",
            phone: "010-2828-1919",
            personalCustomsCode: "P282819191234",
            zipCode: "14998",
            address: "경기도 시흥시 배곧4로 32",
            deliveryMessage: "부재 시 경비실",
        },
        product: {
            id: "PROD-028",
            productOrderId: "GMARKET-PROD-0028",
            name: "책상 모니터 받침대",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "월넛 / 서랍형",
            quantity: 1,
            unitPrice: 45900,
        },
        paymentPrice: 45900,
        platformFee: 1520,
        expectedSettlement: 44380,
        expectedCost: 23800,
        sourcingLifeSyncStatus: "MATCH_SAVED",
        sourcingLifeSyncedAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260617-0028-MATCH-01",
            optionId: "walnut-drawer",
            productId: "SL-P-0028-01",
            productName: "책상 모니터 받침대 서랍형",
            thumbnail: "/images/dummy/tv-stand.png",
            matchRate: 96,
            optionName: "월넛 / 서랍형",
            quantity: 1,
            estimatedCost: 23800,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260617-0028",
        },
    },
    {
        id: "ORD-20260617-0029",
        marketOrderId: "AUCTION-PREP-0029",
        marketType: "auction",
        storeName: "auction_pick_02",
        orderDate: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "강수빈",
        buyerId: "subin_kang",
        buyerPhone: "010-2929-2020",
        recipient: {
            name: "강수빈",
            phone: "010-2929-2020",
            personalCustomsCode: "P292920201234",
            zipCode: "61011",
            address: "광주광역시 북구 첨단연신로 108",
            detailAddress: "1204동 803호",
            deliveryMessage: "파손 주의",
        },
        product: {
            id: "PROD-029",
            productOrderId: "AUCTION-PROD-0029",
            name: "접이식 빨래 건조대",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "대형 / 실버",
            quantity: 1,
            unitPrice: 38900,
        },
        paymentPrice: 38900,
        platformFee: 1270,
        expectedSettlement: 37630,
        expectedCost: 21100,
        sourcingLifeSyncStatus: "PAYMENT_READY",
        sourcingLifeSyncedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        sourcingLifeMatch: {
            candidateId: "ORD-20260617-0029-MATCH-01",
            optionId: "large-silver",
            productId: "SL-P-0029-01",
            productName: "접이식 빨래 건조대 대형",
            thumbnail: "/images/dummy/camping-chair.png",
            matchRate: 91,
            optionName: "대형 / 실버",
            quantity: 1,
            estimatedCost: 21100,
            paymentUrl: "https://www.sourcinglife.co.kr/payment?orderId=ORD-20260617-0029",
        },
    },
    {
        id: "ORD-20260617-0030",
        marketOrderId: "NAVER-WAIT-0030",
        marketType: "naver",
        storeName: "naver_living_01",
        orderDate: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "문지호",
        buyerId: "jiho_moon",
        buyerPhone: "010-3030-2121",
        recipient: {
            name: "문지호",
            phone: "010-3030-2121",
            personalCustomsCode: "P303021211234",
            zipCode: "26464",
            address: "강원특별자치도 원주시 혁신로 19",
            deliveryMessage: "문 앞 배송",
        },
        product: {
            id: "PROD-030",
            productOrderId: "NAVER-PROD-0030",
            name: "차량용 무선 충전 거치대",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "블랙 / 송풍구형",
            quantity: 1,
            unitPrice: 27900,
        },
        paymentPrice: 27900,
        platformFee: 920,
        expectedSettlement: 26980,
        expectedCost: 15400,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "SOURCED",
        sourcingLifeOrderId: "SL-20260617-0030",
        sourcingLifeSyncedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "512606170030",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
        sourcingLifeActualPayment: {
            amount: 15400,
            currency: "KRW",
            paidAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260617-0031",
        marketOrderId: "COUPANG-WAIT-0031",
        marketType: "coupang",
        storeName: "coupang_life_02",
        orderDate: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "오유나",
        buyerId: "yuna_oh",
        buyerPhone: "010-3131-2222",
        recipient: {
            name: "오유나",
            phone: "010-3131-2222",
            personalCustomsCode: "P313122221234",
            zipCode: "31168",
            address: "충청남도 천안시 서북구 불당25로 182",
            deliveryMessage: "택배함",
        },
        product: {
            id: "PROD-031",
            productOrderId: "COUPANG-PROD-0031",
            name: "실리콘 조리도구 세트",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "그레이 / 11종",
            quantity: 1,
            unitPrice: 31900,
        },
        paymentPrice: 31900,
        platformFee: 1050,
        expectedSettlement: 30850,
        expectedCost: 16800,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "CUSTOMS_CLEARANCE",
        sourcingLifeOrderId: "SL-20260617-0031",
        sourcingLifeSyncedAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 16800,
            currency: "KRW",
            paidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606170031",
            receivedAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260617-0032",
        marketOrderId: "11ST-WAIT-0032",
        marketType: "11st",
        storeName: "eleven_home_01",
        orderDate: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "신태준",
        buyerId: "taejun_shin",
        buyerPhone: "010-3232-2323",
        recipient: {
            name: "신태준",
            phone: "010-3232-2323",
            personalCustomsCode: "WRONG-PCCC",
            zipCode: "52725",
            address: "경상남도 진주시 진주대로 501",
            deliveryMessage: "부재 시 문 앞",
        },
        product: {
            id: "PROD-032",
            productOrderId: "11ST-PROD-0032",
            name: "휴대용 캠핑 랜턴",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "카키 / 충전식",
            quantity: 2,
            unitPrice: 18900,
        },
        paymentPrice: 37800,
        platformFee: 1250,
        expectedSettlement: 36550,
        expectedCost: 20400,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "SOURCED",
        sourcingLifeOrderId: "SL-20260617-0032",
        sourcingLifeSyncedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "512606170032",
            receivedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
        sourcingLifeActualPayment: {
            amount: 20400,
            currency: "KRW",
            paidAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        },
    },
    {
        id: "ORD-20260617-0033",
        marketOrderId: "AUCTION-WAIT-0033",
        marketType: "auction",
        storeName: "auction_living_01",
        orderDate: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 9), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        buyerName: "배준호",
        buyerId: "junho_bae",
        buyerPhone: "010-3333-2424",
        recipient: {
            name: "배준호",
            phone: "010-3333-2424",
            personalCustomsCode: "P333324241234",
            zipCode: "54896",
            address: "전북특별자치도 전주시 완산구 홍산로 250",
            deliveryMessage: "경비실 보관",
        },
        product: {
            id: "PROD-033",
            productOrderId: "AUCTION-PROD-0033",
            name: "무타공 욕실 선반",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "블랙 / 60cm",
            quantity: 1,
            unitPrice: 24900,
        },
        paymentPrice: 24900,
        platformFee: 810,
        expectedSettlement: 24090,
        expectedCost: 13700,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "CUSTOMS_CLEARANCE",
        sourcingLifeOrderId: "SL-20260617-0033",
        sourcingLifeSyncedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        sourcingLifeActualPayment: {
            amount: 13700,
            currency: "KRW",
            paidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        },
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "512606170033",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            source: "manual",
        },
    },
    {
        id: "ORD-20260617-0034",
        marketOrderId: "GMARKET-SHIP-0034",
        marketType: "gmarket",
        storeName: "gmarket_daily_02",
        orderDate: format(subHours(now, 12), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 12), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DELIVERY",
        buyerName: "권라희",
        buyerId: "rahee_kwon",
        buyerPhone: "010-3434-2525",
        recipient: {
            name: "권라희",
            phone: "010-3434-2525",
            personalCustomsCode: "P343425251234",
            zipCode: "41566",
            address: "대구광역시 북구 엑스코로 10",
            deliveryMessage: "직접 수령",
        },
        product: {
            id: "PROD-034",
            productOrderId: "GMARKET-PROD-0034",
            name: "스마트 체중계",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "화이트 / 앱연동",
            quantity: 1,
            unitPrice: 32900,
        },
        paymentPrice: 32900,
        platformFee: 1080,
        expectedSettlement: 31820,
        expectedCost: 17800,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "DOMESTIC_SHIPPING",
        sourcingLifeOrderId: "SL-20260617-0034",
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "512606170034",
            receivedAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "manual",
        },
    },
    {
        id: "ORD-20260617-0035",
        marketOrderId: "NAVER-DONE-0035",
        marketType: "naver",
        storeName: "naver_home_02",
        orderDate: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subDays(now, 2), "yyyy-MM-dd HH:mm"),
        status: "DELIVERED",
        marketOrderStatus: "PURCHASE_DECIDED",
        marketPurchaseConfirmedAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        buyerName: "서도윤",
        buyerId: "doyoon_seo",
        buyerPhone: "010-3535-2626",
        recipient: {
            name: "서도윤",
            phone: "010-3535-2626",
            personalCustomsCode: "P353526261234",
            zipCode: "08511",
            address: "서울특별시 금천구 가산디지털1로 168",
            detailAddress: "B동 1502호",
            deliveryMessage: "완료 후 문자",
        },
        product: {
            id: "PROD-035",
            productOrderId: "NAVER-PROD-0035",
            name: "데스크 LED 스탠드",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "블랙 / 밝기조절",
            quantity: 1,
            unitPrice: 42900,
        },
        paymentPrice: 42900,
        platformFee: 1410,
        expectedSettlement: 41490,
        expectedCost: 22900,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "DELIVERED",
        sourcingLifeOrderId: "SL-20260617-0035",
        domesticInvoice: {
            carrier: "우체국택배",
            trackingNumber: "512606170035",
            receivedAt: format(subDays(now, 1), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subDays(now, 1), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
            uploadMode: "auto",
        },
    },
    {
        id: "ORD-20260618-0036",
        marketOrderId: "NAVER-DIRECT-PURCHASE-PENDING-NO-INVOICE-0036",
        marketType: "naver",
        storeName: "naver_living_01",
        orderDate: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DIRECT_DELIVERY",
        buyerName: "김도현",
        buyerId: "dohyun_kim",
        buyerPhone: "010-3636-2727",
        recipient: {
            name: "김도현",
            phone: "010-3636-2727",
            personalCustomsCode: "P363627271234",
            zipCode: "06035",
            address: "서울특별시 강남구 테헤란로 231",
            detailAddress: "1103호",
            deliveryMessage: "직접 전달 전 연락 부탁드립니다.",
        },
        product: {
            id: "PROD-036",
            productOrderId: "NAVER-PROD-DIRECT-0036",
            name: "조립식 책상 방문 설치 상품",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "오크 / 1200mm",
            quantity: 1,
            unitPrice: 189000,
        },
        paymentPrice: 189000,
        platformFee: 6230,
        expectedSettlement: 182770,
        expectedCost: 119000,
        sourcingLifeSyncStatus: "MATCH_SAVED",
        sourcingProgressStage: "MATCHED",
        sourcingLifeSyncedAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
    },
    {
        id: "ORD-20260618-0037",
        marketOrderId: "COUPANG-DIRECT-SOURCED-SHIP-0037",
        marketType: "coupang",
        storeName: "coupang_life_02",
        orderDate: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DIRECT_DELIVERY",
        buyerName: "박서연",
        buyerId: "seoyeon_park",
        buyerPhone: "010-3737-2828",
        recipient: {
            name: "박서연",
            phone: "010-3737-2828",
            personalCustomsCode: "P373728281234",
            zipCode: "07236",
            address: "서울특별시 영등포구 국제금융로 10",
            detailAddress: "2107호",
            deliveryMessage: "업체직송 예정입니다.",
        },
        product: {
            id: "PROD-037",
            productOrderId: "COUPANG-PROD-DIRECT-0037",
            name: "대형 화분 현장 전달 상품",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "화이트 / 대형",
            quantity: 1,
            unitPrice: 76000,
        },
        paymentPrice: 76000,
        platformFee: 2500,
        expectedSettlement: 73500,
        expectedCost: 40800,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "SOURCED",
        sourcingLifeOrderId: "SL-20260618-0037",
        sourcingLifeSyncedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "512606180037",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260618-0038",
        marketOrderId: "NAVER-DIRECT-SHIP-0038",
        marketType: "naver",
        storeName: "naver_home_02",
        orderDate: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 8), "yyyy-MM-dd HH:mm"),
        status: "DELIVERED",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DIRECT_DELIVERY",
        buyerName: "이준혁",
        buyerId: "junhyuk_lee",
        buyerPhone: "010-3838-2929",
        recipient: {
            name: "이준혁",
            phone: "010-3838-2929",
            personalCustomsCode: "P383829291234",
            zipCode: "48059",
            address: "부산광역시 해운대구 센텀중앙로 90",
            deliveryMessage: "오후 6시 이후 직접 전달",
        },
        product: {
            id: "PROD-038",
            productOrderId: "NAVER-PROD-DIRECT-0038",
            name: "맞춤 제작 액자 직접 전달",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "월넛 / A2",
            quantity: 1,
            unitPrice: 89000,
        },
        paymentPrice: 89000,
        platformFee: 2940,
        expectedSettlement: 86060,
        expectedCost: 47400,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "DELIVERED",
        sourcingLifeOrderId: "SL-20260618-0038",
        sourcingLifeSyncedAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "512606180038",
            receivedAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260618-0039",
        marketOrderId: "COUPANG-DIRECT-SHIP-0039",
        marketType: "coupang",
        storeName: "coupang_life_02",
        orderDate: format(subHours(now, 10), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 10), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DIRECT_DELIVERY",
        buyerName: "최유진",
        buyerId: "yujin_choi",
        buyerPhone: "010-3939-3030",
        recipient: {
            name: "최유진",
            phone: "010-3939-3030",
            personalCustomsCode: "P393930301234",
            zipCode: "30121",
            address: "세종특별자치시 도움1로 108",
            deliveryMessage: "업체직송 완료 후 문자",
        },
        product: {
            id: "PROD-039",
            productOrderId: "COUPANG-PROD-DIRECT-0039",
            name: "사무용 의자 업체직송",
            thumbnail: "/images/dummy/robot-vacuum.png",
            optionName: "그레이 / 조립완료",
            quantity: 1,
            unitPrice: 158000,
        },
        paymentPrice: 158000,
        platformFee: 5210,
        expectedSettlement: 152790,
        expectedCost: 92500,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "DOMESTIC_SHIPPING",
        sourcingLifeOrderId: "SL-20260618-0039",
        sourcingLifeSyncedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "우체국택배",
            trackingNumber: "512606180039",
            receivedAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260618-0040",
        marketOrderId: "GMARKET-EXTERNAL-WAIT-0040",
        marketType: "gmarket",
        storeName: "gmarket_daily_02",
        orderDate: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 5), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        marketOrderStatus: "PAYED",
        buyerName: "윤하진",
        buyerId: "hajin_yoon",
        buyerPhone: "010-4040-3131",
        recipient: {
            name: "윤하진",
            phone: "010-4040-3131",
            personalCustomsCode: "P404031311234",
            zipCode: "06236",
            address: "서울특별시 강남구 선릉로 428",
            deliveryMessage: "문 앞 배송",
        },
        product: {
            id: "PROD-040",
            productOrderId: "GMARKET-PROD-EXTERNAL-0040",
            name: "외부 구매 캠핑 테이블",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "우드 / 90cm",
            quantity: 1,
            unitPrice: 54900,
        },
        paymentPrice: 54900,
        platformFee: 1810,
        expectedSettlement: 53090,
        expectedCost: 29600,
        sourcingLifeSyncStatus: "NOT_LINKED",
        sourcingProgressStage: "EXTERNAL_PURCHASE",
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606180040",
            receivedAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
            source: "manual",
        },
    },
    {
        id: "ORD-20260618-0041",
        marketOrderId: "NAVER-CUSTOMS-CHECK-0041",
        marketType: "naver",
        storeName: "naver_living_01",
        orderDate: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        status: "PREPARING",
        buyerName: "정민서",
        buyerId: "minseo_jung",
        buyerPhone: "010-4141-3232",
        recipient: {
            name: "정민서",
            phone: "010-4141-3232",
            personalCustomsCode: "P41413232",
            zipCode: "12925",
            address: "경기도 하남시 미사강변중앙로 190",
            deliveryMessage: "통관부호 확인 후 발송 부탁드립니다.",
        },
        product: {
            id: "PROD-041",
            productOrderId: "NAVER-PROD-CUSTOMS-0041",
            name: "해외소싱 수납 바구니",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "베이지 / 대형",
            quantity: 2,
            unitPrice: 21800,
        },
        paymentPrice: 43600,
        platformFee: 1440,
        expectedSettlement: 42160,
        expectedCost: 22400,
        sourcingLifeSyncStatus: "MATCH_SAVED",
        sourcingProgressStage: "MATCHED",
    },
    {
        id: "ORD-20260618-0042",
        marketOrderId: "NAVER-SOURCING-COURIER-0042",
        marketType: "naver",
        storeName: "naver_home_02",
        orderDate: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        marketOrderStatus: "PAYED",
        buyerName: "강주원",
        buyerId: "juwon_kang",
        buyerPhone: "010-4242-3333",
        recipient: {
            name: "강주원",
            phone: "010-4242-3333",
            personalCustomsCode: "P424233331234",
            zipCode: "10894",
            address: "경기도 파주시 와석순환로 415",
            deliveryMessage: "부재 시 경비실 보관",
        },
        product: {
            id: "PROD-042",
            productOrderId: "NAVER-PROD-SOURCING-0042",
            name: "소싱라이프 구매 수납 정리함",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "화이트 / 4단",
            quantity: 1,
            unitPrice: 46800,
        },
        paymentPrice: 46800,
        platformFee: 1540,
        expectedSettlement: 45260,
        expectedCost: 24100,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "SOURCED",
        sourcingLifeOrderId: "SL-20260618-0042",
        sourcingLifeSyncedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606180042",
            receivedAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260618-0043",
        marketOrderId: "COUPANG-CUSTOMS-WAIT-0043",
        marketType: "coupang",
        storeName: "coupang_life_02",
        orderDate: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 7), "yyyy-MM-dd HH:mm"),
        status: "READY_TO_SHIP",
        marketOrderStatus: "PAYED",
        buyerName: "임수아",
        buyerId: "sua_lim",
        buyerPhone: "010-4343-3434",
        recipient: {
            name: "임수아",
            phone: "010-4343-3434",
            personalCustomsCode: "P434334341234",
            zipCode: "13558",
            address: "경기도 성남시 분당구 판교역로 145",
            deliveryMessage: "배송 전 문자 부탁드립니다.",
        },
        product: {
            id: "PROD-043",
            productOrderId: "COUPANG-PROD-CUSTOMS-0043",
            name: "통관 중 주방 수납 트레이",
            thumbnail: "/images/dummy/cat-tower.png",
            optionName: "그레이 / 3개입",
            quantity: 1,
            unitPrice: 38900,
        },
        paymentPrice: 38900,
        platformFee: 1280,
        expectedSettlement: 37620,
        expectedCost: 20100,
        sourcingLifeSyncStatus: "INVOICE_RECEIVED",
        sourcingProgressStage: "CUSTOMS_CLEARANCE",
        sourcingLifeOrderId: "SL-20260618-0043",
        sourcingLifeSyncedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606180043",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            source: "sourcing_life",
        },
    },
    {
        id: "ORD-20260618-0044",
        marketOrderId: "GMARKET-EXTERNAL-AUTO-SHIP-0044",
        marketType: "gmarket",
        storeName: "gmarket_daily_02",
        orderDate: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 3), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DELIVERY",
        buyerName: "한지우",
        buyerId: "jiwoo_han",
        buyerPhone: "010-4444-3535",
        recipient: {
            name: "한지우",
            phone: "010-4444-3535",
            personalCustomsCode: "P444435351234",
            zipCode: "04524",
            address: "서울특별시 중구 세종대로 110",
            deliveryMessage: "배송 시작 후 연락 부탁드립니다.",
        },
        product: {
            id: "PROD-044",
            productOrderId: "GMARKET-PROD-EXTERNAL-0044",
            name: "외부 구매 접이식 수납장",
            thumbnail: "/images/dummy/tv-stand.png",
            optionName: "화이트 / 4단",
            quantity: 1,
            unitPrice: 62900,
        },
        paymentPrice: 62900,
        platformFee: 2070,
        expectedSettlement: 60830,
        expectedCost: 33800,
        sourcingLifeSyncStatus: "NOT_LINKED",
        sourcingProgressStage: "EXTERNAL_PURCHASE",
        domesticInvoice: {
            carrier: "롯데택배",
            trackingNumber: "408912340044",
            receivedAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
            uploadedToMarketAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
            source: "manual",
            uploadMode: "auto",
        },
    },
    {
        id: "ORD-20260618-0045",
        marketOrderId: "NAVER-DIRECT-EXTERNAL-INVOICE-SHIP-0045",
        marketType: "naver",
        storeName: "naver_living_01",
        orderDate: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 4), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DIRECT_DELIVERY",
        buyerName: "문서준",
        buyerId: "seojun_moon",
        buyerPhone: "010-4545-3636",
        recipient: {
            name: "문서준",
            phone: "010-4545-3636",
            personalCustomsCode: "P454536361234",
            zipCode: "03154",
            address: "서울특별시 종로구 종로 33",
            deliveryMessage: "직접전달 처리 후 배송 진행 중입니다.",
        },
        product: {
            id: "PROD-045",
            productOrderId: "NAVER-PROD-EXTERNAL-DIRECT-0045",
            name: "외부 구매 원목 사이드 테이블",
            thumbnail: "/images/dummy/vintage-lamp.png",
            optionName: "월넛 / 중형",
            quantity: 1,
            unitPrice: 74900,
        },
        paymentPrice: 74900,
        platformFee: 2470,
        expectedSettlement: 72430,
        expectedCost: 42100,
        sourcingLifeSyncStatus: "NOT_LINKED",
        sourcingProgressStage: "EXTERNAL_PURCHASE",
        domesticInvoice: {
            carrier: "한진택배",
            trackingNumber: "789012340045",
            receivedAt: format(subHours(now, 1), "yyyy-MM-dd HH:mm"),
            source: "manual",
        },
    },
    {
        id: "ORD-20260618-0046",
        marketOrderId: "COUPANG-EXTERNAL-DIRECT-SHIP-0046",
        marketType: "coupang",
        storeName: "coupang_life_02",
        orderDate: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        marketPaidAt: format(subHours(now, 6), "yyyy-MM-dd HH:mm"),
        status: "SHIPPING",
        marketOrderStatus: "DELIVERING",
        marketDeliveryMethod: "DIRECT_DELIVERY",
        buyerName: "오하린",
        buyerId: "harin_oh",
        buyerPhone: "010-4646-3737",
        recipient: {
            name: "오하린",
            phone: "010-4646-3737",
            personalCustomsCode: "P464637371234",
            zipCode: "06236",
            address: "서울특별시 강남구 테헤란로 152",
            deliveryMessage: "배송 시작 시 문자 부탁드립니다.",
        },
        product: {
            id: "PROD-046",
            productOrderId: "COUPANG-PROD-EXTERNAL-DIRECT-0046",
            name: "외부 구매 이동식 행거",
            thumbnail: "/images/dummy/camping-chair.png",
            optionName: "블랙 / 1200mm",
            quantity: 1,
            unitPrice: 88900,
        },
        paymentPrice: 88900,
        platformFee: 2930,
        expectedSettlement: 85970,
        expectedCost: 51600,
        sourcingLifeSyncStatus: "NOT_LINKED",
        sourcingProgressStage: "EXTERNAL_PURCHASE",
        domesticInvoice: {
            carrier: "CJ대한통운",
            trackingNumber: "512606180046",
            receivedAt: format(subHours(now, 2), "yyyy-MM-dd HH:mm"),
            source: "manual",
        },
    },
];

const INTENTIONAL_CUSTOMS_MISMATCH_ORDER_IDS = new Set([
    "ORD-20260617-0027",
    "ORD-20260618-0041",
]);

const DEFAULT_SOURCING_FORWARDER = {
    code: "sl-weihai-a",
    name: "소싱라이프 위해 A센터",
    receiverName: "SL-A센터",
    phone: "18663144075",
    address: "중국 산동성 웨이하이시 환취구 경제기술개발구 해빈남로 28호 A동",
};

function isValidPersonalCustomsCode(value?: string) {
    return /^P\d{12}$/.test(value?.trim().toUpperCase() ?? "");
}

function createDemoPersonalCustomsCode(index: number) {
    return `P${String(index + 1).padStart(12, "0")}`;
}

function createDemoSourcingMatch(order: Order) {
    const quantity = Math.max(1, order.product.quantity);
    const estimatedTotal = order.expectedCost ?? order.product.unitPrice * quantity;

    return {
        candidateId: `${order.id}-MATCH-01`,
        optionId: `${order.product.id}-OPTION-01`,
        productId: `SL-${order.product.id}`,
        productName: order.product.name,
        thumbnail: order.product.thumbnail,
        matchRate: 100,
        optionName: order.product.optionName,
        quantity,
        estimatedCost: Math.round(estimatedTotal / quantity),
        paymentUrl: `https://www.sourcinglife.co.kr/payment?orderId=${order.id}`,
    };
}

function normalizeMockOrder(order: Order, index: number): Order {
    const isExternalPurchase = order.sourcingProgressStage === "EXTERNAL_PURCHASE";
    const isPaymentWaiting = order.sourcingLifeSyncStatus === "PAYMENT_READY" || order.sourcingProgressStage === "PAYMENT_WAITING";
    const isMatched = order.sourcingLifeSyncStatus === "MATCH_SAVED" || order.sourcingProgressStage === "MATCHED";
    const isSourcingLifePaid = !isExternalPurchase && (
        order.sourcingLifeSyncStatus === "PAID"
        || order.sourcingLifeSyncStatus === "INVOICE_RECEIVED"
        || Boolean(order.sourcingLifeOrderId)
        || ["SOURCED", "CHINA_SHIPPING", "CUSTOMS_CLEARANCE", "DOMESTIC_SHIPPING", "DELIVERED"].includes(order.sourcingProgressStage ?? "")
    );
    const requiresValidCustomsCode = isPaymentWaiting
        || isSourcingLifePaid
        || ["READY_TO_SHIP", "SHIPPING", "DELIVERED"].includes(order.status);
    const keepIntentionalMismatch = INTENTIONAL_CUSTOMS_MISMATCH_ORDER_IDS.has(order.id)
        && !isPaymentWaiting
        && !isSourcingLifePaid
        && !["READY_TO_SHIP", "SHIPPING", "DELIVERED"].includes(order.status);
    const recipient = requiresValidCustomsCode && !keepIntentionalMismatch && !isValidPersonalCustomsCode(order.recipient.personalCustomsCode)
        ? { ...order.recipient, personalCustomsCode: createDemoPersonalCustomsCode(index) }
        : order.recipient;
    const sourcingLifeMatch = order.sourcingLifeMatch ?? ((isPaymentWaiting || isMatched || isSourcingLifePaid) ? createDemoSourcingMatch(order) : undefined);

    if (isPaymentWaiting) {
        return {
            ...order,
            status: "PREPARING",
            recipient,
            sourcingLifeSyncStatus: "PAYMENT_READY",
            sourcingProgressStage: "PAYMENT_WAITING",
            sourcingLifeMatch,
            sourcingForwarder: order.sourcingForwarder ?? DEFAULT_SOURCING_FORWARDER,
            sourcingPaymentRequestedAt: order.sourcingPaymentRequestedAt ?? order.sourcingLifeSyncedAt ?? order.orderDate,
            sourcingLifeOrderId: undefined,
            sourcingLifeActualPayment: undefined,
            domesticInvoice: undefined,
        };
    }

    if (isSourcingLifePaid) {
        return {
            ...order,
            recipient,
            sourcingProgressStage: order.sourcingProgressStage && !["MATCH_REQUIRED", "MATCH_PENDING_REVIEW", "MATCHED", "PAYMENT_WAITING"].includes(order.sourcingProgressStage)
                ? order.sourcingProgressStage
                : "SOURCED",
            sourcingLifeOrderId: order.sourcingLifeOrderId ?? `SL-${order.id.replace("ORD-", "")}`,
            sourcingLifeMatch,
            sourcingForwarder: order.sourcingForwarder ?? DEFAULT_SOURCING_FORWARDER,
            sourcingLifeActualPayment: order.sourcingLifeActualPayment ?? {
                amount: order.expectedCost ?? sourcingLifeMatch?.estimatedCost ?? 0,
                currency: "KRW",
                paidAt: order.sourcingLifeSyncedAt ?? order.orderDate,
            },
        };
    }

    if (isMatched) {
        return {
            ...order,
            recipient,
            sourcingProgressStage: "MATCHED",
            sourcingLifeMatch,
        };
    }

    return { ...order, recipient };
}

export const mockOrders: Order[] = rawMockOrders.map(normalizeMockOrder);
